nodeLinker: node-modules

packageExtensions:
  "unocss@*":
    peerDependencies:
      "@unocss/core": "*"
      "@unocss/preset-uno": "*"
  "@unocss/inspector@*":
    peerDependencies:
      "vue": "^3.0.0"
